### ISSUE TITLE
footer widget

### ISSUE THREAD

**Issue by brody182** [mattbanks/Genesis-Starter-Child-Theme#16]
did you notice that the footer widget does not display anything in the footer?

**Comment by mattbanks** [comment]
I typically don't use the footer widgets, so I have it pulling from custom Genesis theme options defined in [functions.php](https://github.com/mattbanks/Genesis-Starter-Child-Theme/blob/master/functions.php#L159-L160). You can comment those lines out to disable that and use the standard footer widgets.
