### ISSUE TITLE
Why is pods required for this?

### ISSUE THREAD

**Issue by danieliser** [mattbanks/Genesis-Starter-Child-Theme#18]
Looked through all the theme files and couldn't find anything related to pods other than inclusion in the tgmpa.

Am I missing something as I don't see it stated on the readme either. Or is it safe to remove that requirement. I don't need it so will be forking to remove anyways but what else would need to be removed in that case? Any sass or other code related to pods?

**Comment by mattbanks** [comment]
Totally safe to remove that! I actually have it changed locally to include CFS instead since I'm not using Pods at the moment. I just have my own personal defaults in there for what I use on projects.

**Comment by danieliser** [comment]
@mattbanks - Thanks for the followup. Great work on this btw. Just the grunt/sass setup is worth the download.
