### ISSUE TITLE
No Appearance > Editor when this theme is active

### ISSUE THREAD

**Issue by siwise** [mattbanks/Genesis-Starter-Child-Theme#19]
The Appearance > Editor option doesn't exist. It is there for the standard installed themes and the Genesis parent theme but not the child. Any ideas? Googling is bringing up some solutions but all seem universal not theme specific.

Thanks!

**Comment by siwise** [comment]
Found the solution. I should have found it soon but I will leave this for anyone who gets stumped on it. 
In functions.php comment out or delete `define ( 'DISALLOW_FILE_EDIT', true );`

**Comment by mattbanks** [comment]
Yeah, I turn that off for security purposes on all sites I develop. http://codex.wordpress.org/Hardening_WordPress#Disable_File_Editing

**Comment by siwise** [comment]
Yeah, good call. Thanks for a great theme!
